# Generated by Django 3.0.5 on 2020-05-04 01:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200502_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 1, 35, 35, 194894, tzinfo=utc)),
        ),
    ]
