# Generated by Django 3.0.5 on 2020-05-04 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 1, 36, 52, 29061, tzinfo=utc)),
        ),
    ]
